### ISSUE TITLE
CFLAGS unconditionally set

### ISSUE THREAD

**Issue by flyn-org** [phaag/nfdump#304] opened 2021-08-21 23:14 UTC
The configure.ac file shipped with nfdump unconditionally sets CFLAGS, which prevents overriding its definition:
```
# Checks for programs.
CFLAGS="-g -O3"
```
Could this instead use "?=".

**Comment by flyn-org** [comment] 2021-08-21 23:15
See also https://github.com/openwrt/packages/pull/16421. We had to patch nfdump to get it to compile properly on OpenWrt.

**Comment by dfateyev** [comment] 2022-02-10 21:11
@phaag could you provide more info why "-O2" (or another flag set defined by the user) can be a problem? The commit [ea1958c](https://github.com/phaag/nfdump/commit/ea1958c100f20936d077b435710bb2bea1420b4d) above looks like a suitable solution.
We at Fedora also need to [remove this flag](https://src.fedoraproject.org/rpms/nfdump/blob/rawhide/f/nfdump.spec#_48) to get a more compliant build.

**Comment by phaag** [comment] 2022-02-19 11:33
If you use use "?=" you always get -O2 because many systems set CFLAGS defaults. Therefore you always end up with -O2 or no optimisation at all.

**Comment by dfateyev** [comment] 2022-02-19 17:55
> Therefore you always end up with -O2 or no optimisation at all.

Is it bad if a distribution sets its own flag set?
E.g., as mentioned above, we forcefully [build](https://kojipkgs.fedoraproject.org//work/tasks/5636/82695636/build.log) nfdump with the RHEL and Fedora predefined flag set, according to the requirements in these distributions.

**Comment by phaag** [comment] 2022-02-20 09:58
Oh no - That's perfectly fine. But the problem is not fixed with a simple  "?=".

**Comment by flyn-org** [comment] 2022-02-21 14:01
Isn't that what "?=" is for? See https://www.gnu.org/software/make/manual/html_node/Setting.html.

**Comment by phaag** [comment] 2022-02-22 09:55
Fixed in master branch. Supplied CFLAGS are accepted.

**Closed by phaag** 2022-02-22 09:55 UTC
