### ISSUE TITLE
Issue with NFDUMP 1.6.19 & 1.6.20 - Missing flow output

### ISSUE THREAD

**Issue by Bert-H** [phaag/nfdump#234] opened 2020-07-13 06:57 UTC
Hello,
There appears to be an issue with NFDUMP 1.6.19 & 1.6.20 with Netflow Processing using the "List Flows" option.
I've attached a PDF that describes the issue in more detail.
I have only noticed this issue starting with NFDUMP 1.6.19.
1.6.18 works fine.
It seems to affect data files with NSEL flow records.
Please let me know if you require further detail.

Many thanks. And many thanks for this great software, have been a long-time user (15+ years).
[NFDUMP1.6.20_ISSUE-Github.pdf](https://github.com/phaag/nfdump/files/4911051/NFDUMP1.6.20_ISSUE-Github.pdf)

**Comment by phaag** [comment] 2020-07-18 13:31
May I ask you for a single nfcapd file, where you can reproduce this behaviour? If so please sind it to me by email to the address in the authors file.

**Comment by Bert-H** [comment] 2020-07-20 01:06
I have emailed you the nfcapd files today as requested.

**Comment by phaag** [comment] 2020-07-25 13:09
Thanks! - The issue is fixed in the master repo. A updated release will follow.

**Closed by phaag** 2020-07-25 13:09 UTC

**Comment by Bert-H** [comment] 2020-07-26 23:49
Thanks Peter!

Much appreciated.

 

Best,

Lambert

 
 

Sent: Sunday, July 26, 2020 at 1:09 AM
