### ISSUE TITLE
Compile problem of the latest nfdump 1.6.16

### ISSUE THREAD

**Issue by yafrank** [phaag/nfdump#98] opened 2018-02-08 08:15 UTC
Hi All,
    When trying to compile the nfdump-1.6.16, I get following during ./configure,
[main@nsc nfdump]$ ./configure --enable-nfprofile --enable-nftrack
...
checking pkg-config is at least version 0.9.0... yes
./configure: line 13617: syntax error near unexpected token `fi'
./configure: line 13617: `fi'
     My procedure is as following,
git clone https://github.com/phaag/nfdump.git
cd nfdump
chmod +x autogen.sh
./autogen.sh    # no error raised here
./configure --enable-nfprofile --enable-nftrack
    Is there anything wrong with my environment, say dependencies not met? It's in the CentOS release 6.9 (Final) and the current nfdump-1.6.13 was compiled in the same guest.

Frank Wang

**Comment by servidge** [comment] 2018-02-09 17:44
It seems there is something wrong within the autogen.sh completion.  
My quick fix was to delete the else statement. To clarify: just the "else". 
Somewhare around Line 13616.
After this it compiled without further problems.

**Comment by yafrank** [comment] 2018-02-10 14:25
You're right. After commenting the "else" before line 13616, the configure works. The root cause could be in the autogen.sh.
Thanks!

**Comment by phaag** [comment] 2018-02-11 12:25
Checked on Debian compatible Linux - it configures and compiles without any problems. 
I need to check with a CentOS.

**Comment by gabrielmocan** [comment] 2018-02-22 20:59
I've just tried to compile in a CentOS 7.4 and everything went fine. I cant put compilation logs here if needed.

**Comment by servidge** [comment] 2018-02-23 08:33
I compiled it on an Oracle Linux 6.9. 
I think it depends more on the used shell of the autogen.sh than on other dependencies. 
In my case GNU bash, Version 4.1.2(2)-release (x86_64-redhat-linux-gnu).
If you enter into the empty "else" an "echo hello world" (or delete it like in my case) it compile without any issues.  
So the "else" without any action seems to be the Problem. 
You can reproduce this behaviour with following if/then/else

```
#!/bin/bash
bar=$1
if [ "$bar" = "foo" ]; then
 echo "if - var bar is "$bar
else 
# echo "else - var bar is "$bar
fi
```

**Comment by gabrielmocan** [comment] 2018-02-23 14:58
@servidge I guess autogen.sh uses "sh" per default instead of bash. Excerpt below.

`#!/bin/sh

set -e

case "$(uname)" in
    Darwin)
        LIBTOOLIZE=${LIBTOOLIZE:-glibtoolize}
        ;;
    *)
        LIBTOOLIZE=${LIBTOOLIZE:-libtoolize}
`
So maybe its more related to sh interpreter rather than bash. Can you try doing "bash autogen.sh" instead of "./autogen.sh" in your 4th step so we can eliminate the interpreter variable in this issue?

**Comment by gabrielmocan** [comment] 2018-02-23 15:05
@servidge I guess autogen.sh uses "sh" per default instead of bash. Excerpt below.

```
#!/bin/sh

set -e

case "$(uname)" in
    Darwin)
        LIBTOOLIZE=${LIBTOOLIZE:-glibtoolize}
        ;;
    *)
        LIBTOOLIZE=${LIBTOOLIZE:-libtoolize}
```

So maybe its more related to sh interpreter rather than bash. Can you try doing "bash autogen.sh" instead of "./autogen.sh" in your 4th step so we can eliminate the interpreter variable in this issue?

**Comment by servidge** [comment] 2018-02-23 17:14
Then it's up to the "sh". In my case the "sh" is linked to /bin/bash. On monday I can test other interpreters.
Otherwise it only needs an echo within the last else at the --enable-influxdb checks. This echo should not disturb the sh either.

**Comment by phaag** [comment] 2018-04-01 10:55
Can this considered to be solved? Any open issues?

**Comment by servidge** [comment] 2018-04-04 23:39
Probably next week i can test it with the affected system. How was it solved?

**Comment by servidge** [comment] 2018-04-09 08:39
ok, nothing is changed. The problem still exists.

```
./configure: line 13617: syntax error near unexpected token `fi'
./configure: line 13617: `fi'
```

The native sh does not exist on the system and the used shell (bash) does not handle the else without action well. I can live with the behavior but I think an action within the else part would be more future proof.

**Comment by phaag** [comment] 2018-04-20 10:43
somehow I can not reproduce this. For compatibility among different flavours of *NIX, I'd like to stay with /bin/sh. As configure is automatically created, I would need to fix the corresponding section in configure.ac. I can not see an empty else part here on my system. If you could help out here with more information I'd happily fix it.

**Comment by servidge** [comment] 2018-04-20 11:32
Which files would help? The configure.ac and the generated configure? 
I can provide both files.

**Comment by yafrank** [comment] 2018-04-20 13:00
Here is my configure.ac and configure created in CentOS 6.9 x86 which will fail in ./configure.
[configure_CentOS6_x86.zip](https://github.com/phaag/nfdump/files/1932173/configure_CentOS6_x86.zip)

**Comment by phaag** [comment] 2018-04-20 14:46
Hmm .. seem to be a CentOS related issue. On Debian alike Linuxes and on *BSDs as well as on OSX there is no such _else_. I need first a CentOS VM in order to test that

**Comment by phaag** [comment] 2018-04-20 17:03
Fixed in master. The InfluxDB definition were incomplete.
Update from master or get 1.6.17, coming soon

**Closed by phaag** 2018-04-20 17:03 UTC
