### ISSUE TITLE
Memory leak in nfcapd

### ISSUE THREAD

**Issue by ajt177** [phaag/nfdump#434] opened 2023-03-22 23:12 UTC
I am running nfcapd Version: 1.7.1 (complied from source) on Oracle Linux 7.9

 nfcapd memory usage grows by over 1 GB per hour.

  Command line I am using:   /usr/local/bin/nfcapd -z -D -t 3600 -b 172.30.119.249 -p 10516 -w /data/netflow/ -P /var/run/nfcapd.pid

```
Server memory usage after 14 hours:
                 total        used        free      shared  buff/cache   available
Mem:           7.6G        7.3G        102M        4.9M        167M         75M
Swap:           47G         15G         32G
```

```
Server memory after restarting nfcapd (shows 21 GB memory freed up):
                 total        used        free      shared  buff/cache   available
Mem:           7.6G        412M        7.0G        5.1M        189M        7.0G
Swap:           47G        208M         47G
```

  Any issues what might be causing this, or how to stop it from being an issue.

Thanks
Andrew Thomas

**Comment by phaag** [comment] 2023-03-23 04:26
what arguments are you providing to nfcapd? Could you please provide to command line?

**Comment by ajt177** [comment] 2023-03-23 05:41
Command line I am using:
/usr/local/bin/nfcapd -z -D -t 3600 -b 172.30.119.249 -p 10516 -w /data/netflow/ -P /var/run/nfcapd.pid

**Comment by ajt177** [comment] 2023-03-25 02:45
I ran valgrind on nfcapd, output attached.

[valgrind.txt](https://github.com/phaag/nfdump/files/11067822/valgrind.txt)

**Comment by phaag** [comment] 2023-03-25 09:06
Excellent - that's what I would have proposed - thanks. 
Would you mind to run it again with -t 60 and let it run for an hour if possible. You may zip the output and send it directly to in to the email in the AUTHORS file.

**Comment by phaag** [comment] 2023-03-29 19:24
The issue is fixed in the latest master repo.

**Closed by phaag** 2023-03-29 19:24 UTC
